require('./Wylie')
fs=require('fs')
initHashes()
w = new Wylie(true, true, true, true)
s=fs.readFileSync('kang.txt', 'utf-8').toString()
s = w.toWylie(s)
fs.writeFileSync('wkang.txt', s, 'utf-8')
fs.writeFileSync('rekang.txt', w.fromWylie(s), 'utf-8')
